// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"testing"

	"github.com/team-telnyx/telnyx-cli/internal/mocktest"
	"github.com/team-telnyx/telnyx-cli/internal/requestflag"
)

func TestCallsDial(t *testing.T) {
	t.Skip("Mock server tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"calls", "dial",
		"--connection-id", "7267xxxxxxxxxxxxxx",
		"--from", "+18005550101",
		"--to", "+18005550100 or sip:username@sip.telnyx.com",
		"--answering-machine-detection", "detect",
		"--answering-machine-detection-config", "{after_greeting_silence_millis: 1000, between_words_silence_millis: 1000, greeting_duration_millis: 1000, greeting_silence_duration_millis: 2000, greeting_total_analysis_time_millis: 50000, initial_silence_millis: 1000, maximum_number_of_words: 1000, maximum_word_length_millis: 2000, silence_threshold: 512, total_analysis_time_millis: 5000}",
		"--audio-url", "http://www.example.com/sounds/greeting.wav",
		"--billing-group-id", "f5586561-8ff0-4291-a0ac-84fe544797bd",
		"--bridge-intent=true",
		"--bridge-on-answer=true",
		"--client-state", "aGF2ZSBhIG5pY2UgZGF5ID1d",
		"--command-id", "891510ac-f3e4-11e8-af5b-de00688a4901",
		"--conference-config", "{id: 0ccc7b54-4df3-4bca-a65a-3da1ecc777f0, beep_enabled: on_exit, conference_name: telnyx-conference, early_media: false, end_conference_on_exit: true, hold: true, hold_audio_url: http://example.com/message.wav, hold_media_name: my_media_uploaded_to_media_storage_api, mute: true, soft_end_conference_on_exit: true, start_conference_on_create: false, start_conference_on_enter: true, supervisor_role: whisper, whisper_call_control_ids: [v2:Sg1xxxQ_U3ixxxyXT_VDNI3xxxazZdg6Vxxxs4-GNYxxxVaJPOhFMRQ, v2:qqpb0mmvd-ovhhBr0BUQQn0fld5jIboaaX3-De0DkqXHzbf8d75xkw]}",
		"--custom-header", "{name: head_1, value: val_1}",
		"--custom-header", "{name: head_2, value: val_2}",
		"--dialogflow-config", "{analyze_sentiment: false, partial_automated_agent_reply: false}",
		"--enable-dialogflow=false",
		"--from-display-name", "Company Name",
		"--link-to", "ilditnZK_eVysupV21KzmzN_sM29ygfauQojpm4BgFtfX5hXAcjotg==",
		"--media-encryption", "SRTP",
		"--media-name", "my_media_uploaded_to_media_storage_api",
		"--park-after-unbridge", "self",
		"--preferred-codecs", "G722,PCMU,PCMA,G729,OPUS,VP8,H264",
		"--record", "record-from-answer",
		"--record-channels", "single",
		"--record-custom-file-name", "my_recording_file_name",
		"--record-format", "wav",
		"--record-max-length", "1000",
		"--record-timeout-secs", "100",
		"--record-track", "outbound",
		"--record-trim", "trim-silence",
		"--send-silence-when-idle=true",
		"--sip-auth-password", "password",
		"--sip-auth-username", "username",
		"--sip-header", "{name: User-to-User, value: '12345'}",
		"--sip-region", "Canada",
		"--sip-transport-protocol", "TLS",
		"--sound-modifications", "{octaves: 0.1, pitch: 0.8, semitone: -2, track: both}",
		"--stream-auth-token", "your-auth-token",
		"--stream-bidirectional-codec", "G722",
		"--stream-bidirectional-mode", "rtp",
		"--stream-bidirectional-sampling-rate", "16000",
		"--stream-bidirectional-target-legs", "both",
		"--stream-codec", "PCMA",
		"--stream-establish-before-call-originate=true",
		"--stream-track", "both_tracks",
		"--stream-url", "wss://www.example.com/websocket",
		"--supervise-call-control-id", "v3:MdI91X4lWFEs7IgbBEOT9M4AigoY08M0WWZFISt1Yw2axZ_IiE4pqg",
		"--supervisor-role", "barge",
		"--time-limit-secs", "60",
		"--timeout-secs", "60",
		"--transcription=true",
		"--transcription-config", "{client_state: aGF2ZSBhIG5pY2UgZGF5ID1d, command_id: 891510ac-f3e4-11e8-af5b-de00688a4901, transcription_engine: Google, transcription_engine_config: {enable_speaker_diarization: true, hints: [string], interim_results: true, language: en, max_speaker_count: 4, min_speaker_count: 4, model: latest_long, profanity_filter: true, speech_context: [{boost: 1, phrases: [string]}], transcription_engine: Google, use_enhanced: true}, transcription_tracks: both}",
		"--webhook-url", "https://www.example.com/server-b/",
		"--webhook-url-method", "POST",
	)

	// Check that inner flags have been set up correctly
	requestflag.CheckInnerFlags(callsDial)

	// Alternative argument passing style using inner flags
	mocktest.TestRunMockTestWithFlags(
		t,
		"calls", "dial",
		"--connection-id", "7267xxxxxxxxxxxxxx",
		"--from", "+18005550101",
		"--to", "+18005550100 or sip:username@sip.telnyx.com",
		"--answering-machine-detection", "detect",
		"--answering-machine-detection-config.after-greeting-silence-millis", "1000",
		"--answering-machine-detection-config.between-words-silence-millis", "1000",
		"--answering-machine-detection-config.greeting-duration-millis", "1000",
		"--answering-machine-detection-config.greeting-silence-duration-millis", "2000",
		"--answering-machine-detection-config.greeting-total-analysis-time-millis", "50000",
		"--answering-machine-detection-config.initial-silence-millis", "1000",
		"--answering-machine-detection-config.maximum-number-of-words", "1000",
		"--answering-machine-detection-config.maximum-word-length-millis", "2000",
		"--answering-machine-detection-config.silence-threshold", "512",
		"--answering-machine-detection-config.total-analysis-time-millis", "5000",
		"--audio-url", "http://www.example.com/sounds/greeting.wav",
		"--billing-group-id", "f5586561-8ff0-4291-a0ac-84fe544797bd",
		"--bridge-intent=true",
		"--bridge-on-answer=true",
		"--client-state", "aGF2ZSBhIG5pY2UgZGF5ID1d",
		"--command-id", "891510ac-f3e4-11e8-af5b-de00688a4901",
		"--conference-config.id", "0ccc7b54-4df3-4bca-a65a-3da1ecc777f0",
		"--conference-config.beep-enabled", "on_exit",
		"--conference-config.conference-name", "telnyx-conference",
		"--conference-config.early-media=false",
		"--conference-config.end-conference-on-exit=true",
		"--conference-config.hold=true",
		"--conference-config.hold-audio-url", "http://example.com/message.wav",
		"--conference-config.hold-media-name", "my_media_uploaded_to_media_storage_api",
		"--conference-config.mute=true",
		"--conference-config.soft-end-conference-on-exit=true",
		"--conference-config.start-conference-on-create=false",
		"--conference-config.start-conference-on-enter=true",
		"--conference-config.supervisor-role", "whisper",
		"--conference-config.whisper-call-control-ids", "[v2:Sg1xxxQ_U3ixxxyXT_VDNI3xxxazZdg6Vxxxs4-GNYxxxVaJPOhFMRQ, v2:qqpb0mmvd-ovhhBr0BUQQn0fld5jIboaaX3-De0DkqXHzbf8d75xkw]",
		"--custom-header.name", "head_1",
		"--custom-header.value", "val_1",
		"--custom-header.name", "head_2",
		"--custom-header.value", "val_2",
		"--dialogflow-config.analyze-sentiment=false",
		"--dialogflow-config.partial-automated-agent-reply=false",
		"--enable-dialogflow=false",
		"--from-display-name", "Company Name",
		"--link-to", "ilditnZK_eVysupV21KzmzN_sM29ygfauQojpm4BgFtfX5hXAcjotg==",
		"--media-encryption", "SRTP",
		"--media-name", "my_media_uploaded_to_media_storage_api",
		"--park-after-unbridge", "self",
		"--preferred-codecs", "G722,PCMU,PCMA,G729,OPUS,VP8,H264",
		"--record", "record-from-answer",
		"--record-channels", "single",
		"--record-custom-file-name", "my_recording_file_name",
		"--record-format", "wav",
		"--record-max-length", "1000",
		"--record-timeout-secs", "100",
		"--record-track", "outbound",
		"--record-trim", "trim-silence",
		"--send-silence-when-idle=true",
		"--sip-auth-password", "password",
		"--sip-auth-username", "username",
		"--sip-header.name", "User-to-User",
		"--sip-header.value", "12345",
		"--sip-region", "Canada",
		"--sip-transport-protocol", "TLS",
		"--sound-modifications.octaves", "0.1",
		"--sound-modifications.pitch", "0.8",
		"--sound-modifications.semitone", "-2",
		"--sound-modifications.track", "both",
		"--stream-auth-token", "your-auth-token",
		"--stream-bidirectional-codec", "G722",
		"--stream-bidirectional-mode", "rtp",
		"--stream-bidirectional-sampling-rate", "16000",
		"--stream-bidirectional-target-legs", "both",
		"--stream-codec", "PCMA",
		"--stream-establish-before-call-originate=true",
		"--stream-track", "both_tracks",
		"--stream-url", "wss://www.example.com/websocket",
		"--supervise-call-control-id", "v3:MdI91X4lWFEs7IgbBEOT9M4AigoY08M0WWZFISt1Yw2axZ_IiE4pqg",
		"--supervisor-role", "barge",
		"--time-limit-secs", "60",
		"--timeout-secs", "60",
		"--transcription=true",
		"--transcription-config.client-state", "aGF2ZSBhIG5pY2UgZGF5ID1d",
		"--transcription-config.command-id", "891510ac-f3e4-11e8-af5b-de00688a4901",
		"--transcription-config.transcription-engine", "Google",
		"--transcription-config.transcription-engine-config", "{enable_speaker_diarization: true, hints: [string], interim_results: true, language: en, max_speaker_count: 4, min_speaker_count: 4, model: latest_long, profanity_filter: true, speech_context: [{boost: 1, phrases: [string]}], transcription_engine: Google, use_enhanced: true}",
		"--transcription-config.transcription-tracks", "both",
		"--webhook-url", "https://www.example.com/server-b/",
		"--webhook-url-method", "POST",
	)
}

func TestCallsRetrieveStatus(t *testing.T) {
	t.Skip("Mock server tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"calls", "retrieve-status",
		"--call-control-id", "call_control_id",
	)
}
