// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/team-telnyx/telnyx-cli/internal/apiquery"
	"github.com/team-telnyx/telnyx-cli/internal/requestflag"
	"github.com/team-telnyx/telnyx-go/v4"
	"github.com/team-telnyx/telnyx-go/v4/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var messagingProfilesCreate = requestflag.WithInnerFlags(cli.Command{
	Name:    "create",
	Usage:   "Create a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "name",
			Usage:    "A user friendly name for the messaging profile.",
			Required: true,
			BodyPath: "name",
		},
		&requestflag.Flag[[]string]{
			Name:     "whitelisted-destination",
			Usage:    "Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `[\"*\"]` all destinations will be allowed.",
			Required: true,
			BodyPath: "whitelisted_destinations",
		},
		&requestflag.Flag[any]{
			Name:     "ai-assistant-id",
			Usage:    "The AI assistant ID to associate with this messaging profile.",
			BodyPath: "ai_assistant_id",
		},
		&requestflag.Flag[any]{
			Name:     "alpha-sender",
			Usage:    "The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.",
			BodyPath: "alpha_sender",
		},
		&requestflag.Flag[string]{
			Name:     "daily-spend-limit",
			Usage:    "The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.",
			BodyPath: "daily_spend_limit",
		},
		&requestflag.Flag[bool]{
			Name:     "daily-spend-limit-enabled",
			Usage:    "Whether to enforce the value configured by `daily_spend_limit`.",
			BodyPath: "daily_spend_limit_enabled",
		},
		&requestflag.Flag[bool]{
			Name:     "enabled",
			Usage:    "Specifies whether the messaging profile is enabled or not.",
			Default:  true,
			BodyPath: "enabled",
		},
		&requestflag.Flag[any]{
			Name:     "health-webhook-url",
			Usage:    "A URL to receive health check webhooks for numbers in this profile.",
			BodyPath: "health_webhook_url",
		},
		&requestflag.Flag[bool]{
			Name:     "mms-fall-back-to-sms",
			Usage:    "enables SMS fallback for MMS messages.",
			Default:  false,
			BodyPath: "mms_fall_back_to_sms",
		},
		&requestflag.Flag[bool]{
			Name:     "mms-transcoding",
			Usage:    "enables automated resizing of MMS media.",
			Default:  false,
			BodyPath: "mms_transcoding",
		},
		&requestflag.Flag[bool]{
			Name:     "mobile-only",
			Usage:    "Send messages only to mobile phone numbers.",
			Default:  false,
			BodyPath: "mobile_only",
		},
		&requestflag.Flag[any]{
			Name:     "number-pool-settings",
			Usage:    "Number Pool allows you to send messages from a pool of numbers of different types, assigning\nweights to each type. The pool consists of all the long code and toll free numbers\nassigned to the messaging profile.\n\nTo disable this feature, set the object field to `null`.\n",
			BodyPath: "number_pool_settings",
		},
		&requestflag.Flag[any]{
			Name:     "resource-group-id",
			Usage:    "The resource group ID to associate with this messaging profile.",
			BodyPath: "resource_group_id",
		},
		&requestflag.Flag[bool]{
			Name:     "smart-encoding",
			Usage:    "Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.",
			Default:  false,
			BodyPath: "smart_encoding",
		},
		&requestflag.Flag[any]{
			Name:     "url-shortener-settings",
			Usage:    "The URL shortener feature allows automatic replacement of URLs that were generated using\na public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,\nis.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with\nwith links generated by Telnyx. The use of custom links can improve branding and message\ndeliverability.\n\nTo disable this feature, set the object field to `null`.\n",
			BodyPath: "url_shortener_settings",
		},
		&requestflag.Flag[string]{
			Name:     "webhook-api-version",
			Usage:    "Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.",
			Default:  "2",
			BodyPath: "webhook_api_version",
		},
		&requestflag.Flag[any]{
			Name:     "webhook-failover-url",
			Usage:    "The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.",
			Default:  "",
			BodyPath: "webhook_failover_url",
		},
		&requestflag.Flag[any]{
			Name:     "webhook-url",
			Usage:    "The URL where webhooks related to this messaging profile will be sent.",
			Default:  "",
			BodyPath: "webhook_url",
		},
	},
	Action:          handleMessagingProfilesCreate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"number-pool-settings": {
		&requestflag.InnerFlag[float64]{
			Name:       "number-pool-settings.long-code-weight",
			Usage:      "Defines the probability weight for a Long Code number to be selected when sending a message.\nThe higher the weight the higher the probability. The sum of the weights for all number types\ndoes not necessarily need to add to 100.  Weight must be a non-negative number, and when equal\nto zero it will remove the number type from the pool.\n",
			InnerField: "long_code_weight",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.skip-unhealthy",
			Usage:      "If set to true all unhealthy numbers will be automatically excluded from the pool.\nHealth metrics per number are calculated on a regular basis, taking into account the deliverability\nrate and the amount of messages marked as spam by upstream carriers.\nNumbers with a deliverability rate below 25% or spam ratio over 75% will be considered unhealthy.\n",
			InnerField: "skip_unhealthy",
		},
		&requestflag.InnerFlag[float64]{
			Name:       "number-pool-settings.toll-free-weight",
			Usage:      "Defines the probability weight for a Toll Free number to be selected when sending a message.\nThe higher the weight the higher the probability. The sum of the weights for all number types\ndoes not necessarily need to add to 100. Weight must be a non-negative number, and when equal\nto zero it will remove the number type from the pool.\n",
			InnerField: "toll_free_weight",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.geomatch",
			Usage:      "If set to true, Number Pool will try to choose a sending number with the same area code as the destination\nnumber. If there are no such numbers available, a nunber with a different area code will be chosen. Currently\nonly NANP numbers are supported.\n",
			InnerField: "geomatch",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.sticky-sender",
			Usage:      "If set to true, Number Pool will try to choose the same sending number for all messages to a particular\nrecipient. If the sending number becomes unhealthy and `skip_unhealthy` is set to true, a new\nnumber will be chosen.\n",
			InnerField: "sticky_sender",
		},
	},
	"url-shortener-settings": {
		&requestflag.InnerFlag[string]{
			Name:       "url-shortener-settings.domain",
			Usage:      "One of the domains provided by the Telnyx URL shortener service.\n",
			InnerField: "domain",
		},
		&requestflag.InnerFlag[string]{
			Name:       "url-shortener-settings.prefix",
			Usage:      "Optional prefix that can be used to identify your brand, and will appear in the Telnyx generated URLs after the domain name.\n",
			InnerField: "prefix",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "url-shortener-settings.replace-blacklist-only",
			Usage:      "Use the link replacement tool only for links that are specifically blacklisted by Telnyx.\n",
			InnerField: "replace_blacklist_only",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "url-shortener-settings.send-webhooks",
			Usage:      "Receive webhooks for when your replaced links are clicked. Webhooks are sent to the webhooks on the messaging profile.\n",
			InnerField: "send_webhooks",
		},
	},
})

var messagingProfilesRetrieve = cli.Command{
	Name:    "retrieve",
	Usage:   "Retrieve a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "messaging-profile-id",
			Required: true,
		},
	},
	Action:          handleMessagingProfilesRetrieve,
	HideHelpCommand: true,
}

var messagingProfilesUpdate = requestflag.WithInnerFlags(cli.Command{
	Name:    "update",
	Usage:   "Update a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "messaging-profile-id",
			Required: true,
		},
		&requestflag.Flag[any]{
			Name:     "alpha-sender",
			Usage:    "The alphanumeric sender ID to use when sending to destinations that require an alphanumeric sender ID.",
			BodyPath: "alpha_sender",
		},
		&requestflag.Flag[string]{
			Name:     "daily-spend-limit",
			Usage:    "The maximum amount of money (in USD) that can be spent by this profile before midnight UTC.",
			BodyPath: "daily_spend_limit",
		},
		&requestflag.Flag[bool]{
			Name:     "daily-spend-limit-enabled",
			Usage:    "Whether to enforce the value configured by `daily_spend_limit`.",
			BodyPath: "daily_spend_limit_enabled",
		},
		&requestflag.Flag[bool]{
			Name:     "enabled",
			Usage:    "Specifies whether the messaging profile is enabled or not.",
			BodyPath: "enabled",
		},
		&requestflag.Flag[bool]{
			Name:     "mms-fall-back-to-sms",
			Usage:    "enables SMS fallback for MMS messages.",
			Default:  false,
			BodyPath: "mms_fall_back_to_sms",
		},
		&requestflag.Flag[bool]{
			Name:     "mms-transcoding",
			Usage:    "enables automated resizing of MMS media.",
			Default:  false,
			BodyPath: "mms_transcoding",
		},
		&requestflag.Flag[bool]{
			Name:     "mobile-only",
			Usage:    "Send messages only to mobile phone numbers.",
			Default:  false,
			BodyPath: "mobile_only",
		},
		&requestflag.Flag[string]{
			Name:     "name",
			Usage:    "A user friendly name for the messaging profile.",
			BodyPath: "name",
		},
		&requestflag.Flag[any]{
			Name:     "number-pool-settings",
			Usage:    "Number Pool allows you to send messages from a pool of numbers of different types, assigning\nweights to each type. The pool consists of all the long code and toll free numbers\nassigned to the messaging profile.\n\nTo disable this feature, set the object field to `null`.\n",
			BodyPath: "number_pool_settings",
		},
		&requestflag.Flag[bool]{
			Name:     "smart-encoding",
			Usage:    "Enables automatic character encoding optimization for SMS messages. When enabled, the system automatically selects the most efficient encoding (GSM-7 or UCS-2) based on message content to maximize character limits and minimize costs.",
			Default:  false,
			BodyPath: "smart_encoding",
		},
		&requestflag.Flag[any]{
			Name:     "url-shortener-settings",
			Usage:    "The URL shortener feature allows automatic replacement of URLs that were generated using\na public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly,\nis.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with\nwith links generated by Telnyx. The use of custom links can improve branding and message\ndeliverability.\n\nTo disable this feature, set the object field to `null`.\n",
			BodyPath: "url_shortener_settings",
		},
		&requestflag.Flag[string]{
			Name:     "v1-secret",
			Usage:    "Secret used to authenticate with v1 endpoints.",
			BodyPath: "v1_secret",
		},
		&requestflag.Flag[string]{
			Name:     "webhook-api-version",
			Usage:    "Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.",
			BodyPath: "webhook_api_version",
		},
		&requestflag.Flag[any]{
			Name:     "webhook-failover-url",
			Usage:    "The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.",
			BodyPath: "webhook_failover_url",
		},
		&requestflag.Flag[any]{
			Name:     "webhook-url",
			Usage:    "The URL where webhooks related to this messaging profile will be sent.",
			BodyPath: "webhook_url",
		},
		&requestflag.Flag[[]string]{
			Name:     "whitelisted-destination",
			Usage:    "Destinations to which the messaging profile is allowed to send. The elements in the list must be valid ISO 3166-1 alpha-2 country codes. If set to `[\"*\"]`, all destinations will be allowed.\n\nThis field is required if the messaging profile doesn't have it defined yet.",
			BodyPath: "whitelisted_destinations",
		},
	},
	Action:          handleMessagingProfilesUpdate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"number-pool-settings": {
		&requestflag.InnerFlag[float64]{
			Name:       "number-pool-settings.long-code-weight",
			Usage:      "Defines the probability weight for a Long Code number to be selected when sending a message.\nThe higher the weight the higher the probability. The sum of the weights for all number types\ndoes not necessarily need to add to 100.  Weight must be a non-negative number, and when equal\nto zero it will remove the number type from the pool.\n",
			InnerField: "long_code_weight",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.skip-unhealthy",
			Usage:      "If set to true all unhealthy numbers will be automatically excluded from the pool.\nHealth metrics per number are calculated on a regular basis, taking into account the deliverability\nrate and the amount of messages marked as spam by upstream carriers.\nNumbers with a deliverability rate below 25% or spam ratio over 75% will be considered unhealthy.\n",
			InnerField: "skip_unhealthy",
		},
		&requestflag.InnerFlag[float64]{
			Name:       "number-pool-settings.toll-free-weight",
			Usage:      "Defines the probability weight for a Toll Free number to be selected when sending a message.\nThe higher the weight the higher the probability. The sum of the weights for all number types\ndoes not necessarily need to add to 100. Weight must be a non-negative number, and when equal\nto zero it will remove the number type from the pool.\n",
			InnerField: "toll_free_weight",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.geomatch",
			Usage:      "If set to true, Number Pool will try to choose a sending number with the same area code as the destination\nnumber. If there are no such numbers available, a nunber with a different area code will be chosen. Currently\nonly NANP numbers are supported.\n",
			InnerField: "geomatch",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "number-pool-settings.sticky-sender",
			Usage:      "If set to true, Number Pool will try to choose the same sending number for all messages to a particular\nrecipient. If the sending number becomes unhealthy and `skip_unhealthy` is set to true, a new\nnumber will be chosen.\n",
			InnerField: "sticky_sender",
		},
	},
	"url-shortener-settings": {
		&requestflag.InnerFlag[string]{
			Name:       "url-shortener-settings.domain",
			Usage:      "One of the domains provided by the Telnyx URL shortener service.\n",
			InnerField: "domain",
		},
		&requestflag.InnerFlag[string]{
			Name:       "url-shortener-settings.prefix",
			Usage:      "Optional prefix that can be used to identify your brand, and will appear in the Telnyx generated URLs after the domain name.\n",
			InnerField: "prefix",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "url-shortener-settings.replace-blacklist-only",
			Usage:      "Use the link replacement tool only for links that are specifically blacklisted by Telnyx.\n",
			InnerField: "replace_blacklist_only",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "url-shortener-settings.send-webhooks",
			Usage:      "Receive webhooks for when your replaced links are clicked. Webhooks are sent to the webhooks on the messaging profile.\n",
			InnerField: "send_webhooks",
		},
	},
})

var messagingProfilesList = requestflag.WithInnerFlags(cli.Command{
	Name:    "list",
	Usage:   "List messaging profiles",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[map[string]any]{
			Name:      "filter",
			Usage:     "Consolidated filter parameter (deepObject style). Originally: filter[name]",
			QueryPath: "filter",
		},
		&requestflag.Flag[string]{
			Name:      "filter-name-contains",
			Usage:     "Filter profiles by name containing the given string.",
			QueryPath: "filter[name][contains]",
		},
		&requestflag.Flag[string]{
			Name:      "filter-name-eq",
			Usage:     "Filter profiles by exact name match.",
			QueryPath: "filter[name][eq]",
		},
		&requestflag.Flag[int64]{
			Name:      "page-number",
			QueryPath: "page[number]",
		},
		&requestflag.Flag[int64]{
			Name:      "page-size",
			QueryPath: "page[size]",
		},
	},
	Action:          handleMessagingProfilesList,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"filter": {
		&requestflag.InnerFlag[string]{
			Name:       "filter.name",
			Usage:      "Filter by name",
			InnerField: "name",
		},
	},
})

var messagingProfilesDelete = cli.Command{
	Name:    "delete",
	Usage:   "Delete a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "messaging-profile-id",
			Required: true,
		},
	},
	Action:          handleMessagingProfilesDelete,
	HideHelpCommand: true,
}

var messagingProfilesListAlphanumericSenderIDs = cli.Command{
	Name:    "list-alphanumeric-sender-ids",
	Usage:   "List all alphanumeric sender IDs associated with a specific messaging profile.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "id",
			Required: true,
		},
		&requestflag.Flag[int64]{
			Name:      "page-number",
			Default:   1,
			QueryPath: "page[number]",
		},
		&requestflag.Flag[int64]{
			Name:      "page-size",
			Default:   20,
			QueryPath: "page[size]",
		},
	},
	Action:          handleMessagingProfilesListAlphanumericSenderIDs,
	HideHelpCommand: true,
}

var messagingProfilesListPhoneNumbers = cli.Command{
	Name:    "list-phone-numbers",
	Usage:   "List phone numbers associated with a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "messaging-profile-id",
			Required: true,
		},
		&requestflag.Flag[int64]{
			Name:      "page-number",
			QueryPath: "page[number]",
		},
		&requestflag.Flag[int64]{
			Name:      "page-size",
			QueryPath: "page[size]",
		},
	},
	Action:          handleMessagingProfilesListPhoneNumbers,
	HideHelpCommand: true,
}

var messagingProfilesListShortCodes = cli.Command{
	Name:    "list-short-codes",
	Usage:   "List short codes associated with a messaging profile",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "messaging-profile-id",
			Required: true,
		},
		&requestflag.Flag[int64]{
			Name:      "page-number",
			QueryPath: "page[number]",
		},
		&requestflag.Flag[int64]{
			Name:      "page-size",
			QueryPath: "page[size]",
		},
	},
	Action:          handleMessagingProfilesListShortCodes,
	HideHelpCommand: true,
}

var messagingProfilesRetrieveMetrics = cli.Command{
	Name:    "retrieve-metrics",
	Usage:   "Get detailed metrics for a specific messaging profile, broken down by time\ninterval.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "id",
			Required: true,
		},
		&requestflag.Flag[string]{
			Name:      "time-frame",
			Usage:     "The time frame for metrics.",
			Default:   "24h",
			QueryPath: "time_frame",
		},
	},
	Action:          handleMessagingProfilesRetrieveMetrics,
	HideHelpCommand: true,
}

func handleMessagingProfilesCreate(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileNewParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.MessagingProfiles.New(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-profiles create", obj, format, transform)
}

func handleMessagingProfilesRetrieve(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("messaging-profile-id") && len(unusedArgs) > 0 {
		cmd.Set("messaging-profile-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.MessagingProfiles.Get(ctx, cmd.Value("messaging-profile-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-profiles retrieve", obj, format, transform)
}

func handleMessagingProfilesUpdate(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("messaging-profile-id") && len(unusedArgs) > 0 {
		cmd.Set("messaging-profile-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileUpdateParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.MessagingProfiles.Update(
		ctx,
		cmd.Value("messaging-profile-id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-profiles update", obj, format, transform)
}

func handleMessagingProfilesList(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileListParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	if format == "raw" {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.MessagingProfiles.List(ctx, params, options...)
		if err != nil {
			return err
		}
		obj := gjson.ParseBytes(res)
		return ShowJSON(os.Stdout, "messaging-profiles list", obj, format, transform)
	} else {
		iter := client.MessagingProfiles.ListAutoPaging(ctx, params, options...)
		return ShowJSONIterator(os.Stdout, "messaging-profiles list", iter, format, transform)
	}
}

func handleMessagingProfilesDelete(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("messaging-profile-id") && len(unusedArgs) > 0 {
		cmd.Set("messaging-profile-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.MessagingProfiles.Delete(ctx, cmd.Value("messaging-profile-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-profiles delete", obj, format, transform)
}

func handleMessagingProfilesListAlphanumericSenderIDs(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("id") && len(unusedArgs) > 0 {
		cmd.Set("id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileListAlphanumericSenderIDsParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	if format == "raw" {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.MessagingProfiles.ListAlphanumericSenderIDs(
			ctx,
			cmd.Value("id").(string),
			params,
			options...,
		)
		if err != nil {
			return err
		}
		obj := gjson.ParseBytes(res)
		return ShowJSON(os.Stdout, "messaging-profiles list-alphanumeric-sender-ids", obj, format, transform)
	} else {
		iter := client.MessagingProfiles.ListAlphanumericSenderIDsAutoPaging(
			ctx,
			cmd.Value("id").(string),
			params,
			options...,
		)
		return ShowJSONIterator(os.Stdout, "messaging-profiles list-alphanumeric-sender-ids", iter, format, transform)
	}
}

func handleMessagingProfilesListPhoneNumbers(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("messaging-profile-id") && len(unusedArgs) > 0 {
		cmd.Set("messaging-profile-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileListPhoneNumbersParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	if format == "raw" {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.MessagingProfiles.ListPhoneNumbers(
			ctx,
			cmd.Value("messaging-profile-id").(string),
			params,
			options...,
		)
		if err != nil {
			return err
		}
		obj := gjson.ParseBytes(res)
		return ShowJSON(os.Stdout, "messaging-profiles list-phone-numbers", obj, format, transform)
	} else {
		iter := client.MessagingProfiles.ListPhoneNumbersAutoPaging(
			ctx,
			cmd.Value("messaging-profile-id").(string),
			params,
			options...,
		)
		return ShowJSONIterator(os.Stdout, "messaging-profiles list-phone-numbers", iter, format, transform)
	}
}

func handleMessagingProfilesListShortCodes(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("messaging-profile-id") && len(unusedArgs) > 0 {
		cmd.Set("messaging-profile-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileListShortCodesParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	if format == "raw" {
		var res []byte
		options = append(options, option.WithResponseBodyInto(&res))
		_, err = client.MessagingProfiles.ListShortCodes(
			ctx,
			cmd.Value("messaging-profile-id").(string),
			params,
			options...,
		)
		if err != nil {
			return err
		}
		obj := gjson.ParseBytes(res)
		return ShowJSON(os.Stdout, "messaging-profiles list-short-codes", obj, format, transform)
	} else {
		iter := client.MessagingProfiles.ListShortCodesAutoPaging(
			ctx,
			cmd.Value("messaging-profile-id").(string),
			params,
			options...,
		)
		return ShowJSONIterator(os.Stdout, "messaging-profiles list-short-codes", iter, format, transform)
	}
}

func handleMessagingProfilesRetrieveMetrics(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("id") && len(unusedArgs) > 0 {
		cmd.Set("id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.MessagingProfileGetMetricsParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.MessagingProfiles.GetMetrics(
		ctx,
		cmd.Value("id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-profiles retrieve-metrics", obj, format, transform)
}
