// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/stainless-sdks/telnyx-cli/internal/apiquery"
	"github.com/stainless-sdks/telnyx-cli/internal/requestflag"
	"github.com/team-telnyx/telnyx-go/v4"
	"github.com/team-telnyx/telnyx-go/v4/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var messaging10dlcCampaignBuilderSubmit = cli.Command{
	Name:    "submit",
	Usage:   "Before creating a campaign, use the\n[Qualify By Usecase endpoint](https://developers.telnyx.com/api-reference/campaign/qualify-by-usecase)\nto ensure that the brand you want to assign a new campaign to is qualified for\nthe desired use case of that campaign. **Please note:** After campaign creation,\nyou'll only be able to edit the campaign's sample messages. Creating a campaign\nwill entail an upfront, non-refundable three month's cost that will depend on\nthe campaign's use case\n([see 10DLC Costs section for details](https://developers.telnyx.com/api-reference/campaign/get-campaign-cost)).",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "brand-id",
			Usage:    "Alphanumeric identifier of the brand associated with this campaign.",
			Required: true,
			BodyPath: "brandId",
		},
		&requestflag.Flag[string]{
			Name:     "description",
			Usage:    "Summary description of this campaign.",
			Required: true,
			BodyPath: "description",
		},
		&requestflag.Flag[string]{
			Name:     "usecase",
			Usage:    "Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase` operation to retrieve usecases available for given brand.",
			Required: true,
			BodyPath: "usecase",
		},
		&requestflag.Flag[bool]{
			Name:     "age-gated",
			Usage:    "Age gated message content in campaign.",
			BodyPath: "ageGated",
		},
		&requestflag.Flag[bool]{
			Name:     "auto-renewal",
			Usage:    "Campaign subscription auto-renewal option. If set to true, then campaign will automatically renewal at end of billing cycle.",
			BodyPath: "autoRenewal",
		},
		&requestflag.Flag[bool]{
			Name:     "direct-lending",
			Usage:    "Direct lending or loan arrangement",
			BodyPath: "directLending",
		},
		&requestflag.Flag[bool]{
			Name:     "embedded-link",
			Usage:    "Does message generated by the campaign include URL link in SMS?",
			BodyPath: "embeddedLink",
		},
		&requestflag.Flag[string]{
			Name:     "embedded-link-sample",
			Usage:    "Sample of an embedded link that will be sent to subscribers.",
			BodyPath: "embeddedLinkSample",
		},
		&requestflag.Flag[bool]{
			Name:     "embedded-phone",
			Usage:    "Does message generated by the campaign include phone number in SMS?",
			BodyPath: "embeddedPhone",
		},
		&requestflag.Flag[string]{
			Name:     "help-keywords",
			Usage:    "Subscriber help keywords. Multiple keywords are comma separated without space.",
			BodyPath: "helpKeywords",
		},
		&requestflag.Flag[string]{
			Name:     "help-message",
			Usage:    "Help message of the campaign.",
			BodyPath: "helpMessage",
		},
		&requestflag.Flag[string]{
			Name:     "message-flow",
			Usage:    "Message flow description.",
			BodyPath: "messageFlow",
		},
		&requestflag.Flag[[]int64]{
			Name:     "mno-id",
			Usage:    "Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs if no value provided.",
			BodyPath: "mnoIds",
		},
		&requestflag.Flag[bool]{
			Name:     "number-pool",
			Usage:    "Does campaign utilize pool of phone numbers?",
			BodyPath: "numberPool",
		},
		&requestflag.Flag[string]{
			Name:     "optin-keywords",
			Usage:    "Subscriber opt-in keywords. Multiple keywords are comma separated without space.",
			BodyPath: "optinKeywords",
		},
		&requestflag.Flag[string]{
			Name:     "optin-message",
			Usage:    "Subscriber opt-in message.",
			BodyPath: "optinMessage",
		},
		&requestflag.Flag[string]{
			Name:     "optout-keywords",
			Usage:    "Subscriber opt-out keywords. Multiple keywords are comma separated without space.",
			BodyPath: "optoutKeywords",
		},
		&requestflag.Flag[string]{
			Name:     "optout-message",
			Usage:    "Subscriber opt-out message.",
			BodyPath: "optoutMessage",
		},
		&requestflag.Flag[string]{
			Name:     "privacy-policy-link",
			Usage:    "Link to the campaign's privacy policy.",
			BodyPath: "privacyPolicyLink",
		},
		&requestflag.Flag[string]{
			Name:     "reference-id",
			Usage:    "Caller supplied campaign reference ID. If supplied, the value must be unique across all submitted campaigns. Can be used to prevent duplicate campaign registrations.",
			BodyPath: "referenceId",
		},
		&requestflag.Flag[string]{
			Name:     "reseller-id",
			Usage:    "Alphanumeric identifier of the reseller that you want to associate with this campaign.",
			BodyPath: "resellerId",
		},
		&requestflag.Flag[string]{
			Name:     "sample1",
			Usage:    "Message sample. Some campaign tiers require 1 or more message samples.",
			BodyPath: "sample1",
		},
		&requestflag.Flag[string]{
			Name:     "sample2",
			Usage:    "Message sample. Some campaign tiers require 2 or more message samples.",
			BodyPath: "sample2",
		},
		&requestflag.Flag[string]{
			Name:     "sample3",
			Usage:    "Message sample. Some campaign tiers require 3 or more message samples.",
			BodyPath: "sample3",
		},
		&requestflag.Flag[string]{
			Name:     "sample4",
			Usage:    "Message sample. Some campaign tiers require 4 or more message samples.",
			BodyPath: "sample4",
		},
		&requestflag.Flag[string]{
			Name:     "sample5",
			Usage:    "Message sample. Some campaign tiers require 5 or more message samples.",
			BodyPath: "sample5",
		},
		&requestflag.Flag[bool]{
			Name:     "subscriber-help",
			Usage:    "Does campaign responds to help keyword(s)?",
			BodyPath: "subscriberHelp",
		},
		&requestflag.Flag[bool]{
			Name:     "subscriber-optin",
			Usage:    "Does campaign require subscriber to opt-in before SMS is sent to subscriber?",
			BodyPath: "subscriberOptin",
		},
		&requestflag.Flag[bool]{
			Name:     "subscriber-optout",
			Usage:    "Does campaign support subscriber opt-out keyword(s)?",
			BodyPath: "subscriberOptout",
		},
		&requestflag.Flag[[]string]{
			Name:     "sub-usecase",
			Usage:    "Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/10dlc/enum/usecase` operation to retrieve list of valid sub-usecases",
			BodyPath: "subUsecases",
		},
		&requestflag.Flag[[]string]{
			Name:     "tag",
			Usage:    "Tags to be set on the Campaign.",
			BodyPath: "tag",
		},
		&requestflag.Flag[bool]{
			Name:     "terms-and-conditions",
			Usage:    "Is terms and conditions accepted?",
			BodyPath: "termsAndConditions",
		},
		&requestflag.Flag[string]{
			Name:     "terms-and-conditions-link",
			Usage:    "Link to the campaign's terms and conditions.",
			BodyPath: "termsAndConditionsLink",
		},
		&requestflag.Flag[string]{
			Name:     "webhook-failover-url",
			Usage:    "Failover webhook to which campaign status updates are sent.",
			BodyPath: "webhookFailoverURL",
		},
		&requestflag.Flag[string]{
			Name:     "webhook-url",
			Usage:    "Webhook to which campaign status updates are sent.",
			BodyPath: "webhookURL",
		},
	},
	Action:          handleMessaging10dlcCampaignBuilderSubmit,
	HideHelpCommand: true,
}

func handleMessaging10dlcCampaignBuilderSubmit(ctx context.Context, cmd *cli.Command) error {
	client := telnyx.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := telnyx.Messaging10dlcCampaignBuilderSubmitParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Messaging10dlc.CampaignBuilder.Submit(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, "messaging-10dlc:campaign-builder submit", obj, format, transform)
}
