#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/team-telnyx/telnyx-go/v4,github.com/stainless-sdks/telnyx-go/v4"

REPLACEMENT="${1:-"../telnyx-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/team-telnyx/telnyx-go/v4="$REPLACEMENT"
go mod tidy -e
